### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by dlongley**

### CODE REVIEW

**Comment by mattcollier** [comment]
It would be good to get this issue addressed before merge: https://github.com/digitalbazaar/bedrock-manifest-proxy/issues/4

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Comment by mattcollier** [comment]
As I mentioned earlier, axios needs to be replaced here per #4.  There are CVEs for the version of axios currently in use here.

**Comment by dlongley** [comment]
This can be used as a template to replace `axios` with `@digitalbazaar/http-client`: https://github.com/digitalbazaar/authn.io/blob/43f44beb9b357a1cf26b28df67ed6ff6a80371d0/lib/http.js

**Pull request merged**
